CREATE TABLE [dbo].[SAPConsumoReal] (
    [Centro]             NVARCHAR (4)  NULL,
    [Sociedad]           NVARCHAR (4)  NULL,
    [Ano]                INT           NULL,
    [Mes]                INT           NULL,
    [Nivel]              REAL          NULL,
    [MaterialPpal]       NVARCHAR (18) NULL,
    [VersionFabricacion] NVARCHAR (4)  NULL,
    [Orden]              NVARCHAR (22) NULL,
    [PuestoTrabajo]      NVARCHAR (8)  NULL,
    [MaterialCons]       NVARCHAR (18) NULL,
    [PesoBruto]          REAL          NULL,
    [PesoNeto]           REAL          NULL,
    [UnidadPeso]         NVARCHAR (3)  NULL,
    [UnidadBase]         NVARCHAR (3)  NULL,
    [ClaseAprov]         NVARCHAR (1)  NULL,
    [ClaseAprovEsp]      NVARCHAR (2)  NULL,
    [CosteStd]           REAL          NULL,
    [BaseCoste]          REAL          NULL,
    [PosListaMat]        NVARCHAR (4)  NULL,
    [CantComponente]     REAL          NULL,
    [UnidadComponente]   NVARCHAR (3)  NULL,
    [Pedido]             NVARCHAR (10) NULL,
    [PedidoPos]          INT           NULL,
    [PrecioNeto]         REAL          NULL,
    [UnidadPrecio]       NVARCHAR (3)  NULL,
    [Proveedor]          NVARCHAR (10) NULL,
    [CantidadTotal]      REAL          NULL
);

