CREATE TABLE [dbo].[z_ExcelInversionesBPC] (
    [Anio]                  INT            NULL,
    [CodSociedad]           NVARCHAR (255) NULL,
    [CodInversion]          NVARCHAR (255) NULL,
    [Descripcion]           NVARCHAR (255) NULL,
    [PresupuestoEnero]      FLOAT (53)     NULL,
    [PresupuestoFebrero]    FLOAT (53)     NULL,
    [PresupuestoMarzo]      FLOAT (53)     NULL,
    [PresupuestoAbril]      FLOAT (53)     NULL,
    [PresupuestoMayo]       FLOAT (53)     NULL,
    [PresupuestoJunio]      FLOAT (53)     NULL,
    [PresupuestoJulio]      FLOAT (53)     NULL,
    [PresupuestoAgosto]     FLOAT (53)     NULL,
    [PresupuestoSeptiembre] FLOAT (53)     NULL,
    [PresupuestoOctubre]    FLOAT (53)     NULL,
    [PresupuestoNoviembre]  FLOAT (53)     NULL,
    [PresupuestoDiciembre]  FLOAT (53)     NULL,
    [RealEnero]             FLOAT (53)     NULL,
    [RealFebrero]           FLOAT (53)     NULL,
    [RealMarzo]             FLOAT (53)     NULL,
    [RealAbril]             FLOAT (53)     NULL,
    [RealMayo]              FLOAT (53)     NULL,
    [RealJunio]             FLOAT (53)     NULL,
    [RealJulio]             FLOAT (53)     NULL,
    [RealAgosto]            FLOAT (53)     NULL,
    [RealSeptiembre]        FLOAT (53)     NULL,
    [RealOctubre]           FLOAT (53)     NULL,
    [RealNoviembre]         FLOAT (53)     NULL,
    [RealDiciembre]         FLOAT (53)     NULL
);

