
CREATE VIEW [dbo].[Fact_Autocontroles]
AS
  WITH ac
       AS (SELECT centro,
                  fechaimputacion,
                  puestotrabajo,
                  orden,
                  turno,
                  operario,
                  autocontrol,
                  norma,
                  nombrenorma,
                  anotacion,
                  valor,
                  ValorNominal,
                  ToleranciaMinima,
                  ToleranciaMaxima,
                  TolMinCliente,
                  TolMaxCliente,
                  atributo,
                  tipoautocontrol,
                  descripcionnorma,
                  notasnorma,
                  ''              AS ModoLanzamiento,
                  ''              AS ExpiraAutomaticamente,
                  ''              AS TiempoExpiracion,
                  'Autocontroles' AS Tipo
           FROM   dbo.autocontroles
           UNION ALL
           SELECT centro,
                  fechaimputacion,
                  puestotrabajo,
                  orden,
                  turno,
                  operario,
                  autocontrol,
                  norma,
                  nombrenorma,
                  anotacion,
                  valor,
                  null as ValorNominal,
                  null as ToleranciaMinima,
                  null as ToleranciaMaxima,
                  null as TolMinCliente,
                  null as TolMaxCliente,
                  atributo,
                  tipoautocontrol,
                  descripcionnorma,
                  notasnorma,
                  ''                       AS ModoLanzamiento,
                  ''                       AS ExpiraAutomaticamente,
                  ''                       AS TiempoExpiracion,
                  'AutocontrolesSinCubrir' AS Tipo
           FROM   dbo.autocontrolessincubrir
           UNION ALL
           SELECT centro,
                  fechaimputacion,
                  puestotrabajo,
                  orden,
                  turno,
                  operario,
                  autocontrol,
                  norma,
                  nombrenorma,
                  anotacion,
                  0                        AS Valor,
                  null as ValorNominal,
                  null as ToleranciaMinima,
                  null as ToleranciaMaxima,
                  null as TolMinCliente,
                  null as TolMaxCliente,
                  ''                       AS Atributo,
                  nombreautocontrol        AS TipoAutocontrol,
                  descripcionnorma,
                  ''                       AS NotasNorma,
                  modolanzamiento,
                  expiraautomaticamente,
                  tiempoexpiracion,
                  'AutocontrolesExpirados' AS Tipo
           FROM   dbo.autocontrolesexpirados)
  SELECT AC_1.centro + '-' + AC_1.puestotrabajo AS CenPue_Id,
         AC_1.centro + '-' + AC_1.orden         AS CenOrd_Id,
         AC_1.centro + '-' + AC_1.norma         AS CenNor_Id,
         AC_1.centro + '-' + AC_1.turno         AS CenTur_Id,
         AC_1.centro + '-' + AC_1.operario      AS CenOpe_Id,
         AC_1.centro + '-' + O.material         AS CenMat_Id,
         AC_1.centro,
         AC_1.fechaimputacion                   AS [Fecha Imputación],
         AC_1.autocontrol,
         AC_1.anotacion                         AS Anotación,
         AC_1.valor,
         AC_1.ToleranciaMinima                  AS [Tolerancia Mínima],
         AC_1.ToleranciaMaxima                  AS [Tolerancia Máxima],
         AC_1.TolMinCliente                     AS [Tolerancia Mínima Cliente],
         AC_1.TolMaxCliente                     AS [Tolerancia Máxima Cliente],
         AC_1.atributo,
         AC_1.tipoautocontrol                   AS [Tipo Autocontrol],
         AC_1.notasnorma                        AS [Notas Norma],
         AC_1.modolanzamiento                   AS [Modo Lanzamiento],
         AC_1.expiraautomaticamente             AS [Expira Automáticamente],
         AC_1.tiempoexpiracion                  AS [Tiempo Expiración],
         AC_1.tipo
  FROM   ac AS AC_1
         LEFT OUTER JOIN dbo.ofcaptor AS O
                      ON AC_1.centro = O.centro
                         AND AC_1.orden = O.ordencaptor
  WHERE  ( AC_1.fechaimputacion >= (SELECT fecha
                                    FROM   dbo.fechaconsulta) )